# Generated by Django 3.1.4 on 2020-12-17 21:16

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Краткое описание категории')),
                ('slug', models.SlugField(help_text='только маленькие латинские буквы, без пробелов и спец символов', unique=True, verbose_name='Slug')),
                ('order', models.PositiveSmallIntegerField(help_text='Будет использоваться для сортировки', verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Краткое описание поста')),
                ('image', models.URLField(verbose_name='Изображение')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Тело поста')),
                ('rating', models.PositiveSmallIntegerField(default=10, verbose_name='Рейтинг поста от 1 до 10')),
                ('future', models.BooleanField(default=False, verbose_name='Рекомендовать')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('order', models.PositiveSmallIntegerField(help_text='Будет использоваться для сортировки', verbose_name='Порядковый номер')),
                ('slug', models.SlugField(help_text='только маленькие латинские буквы, без пробелов и спец символов', unique=True, verbose_name='Slug')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('views', models.PositiveSmallIntegerField(default=0, verbose_name='Количество просмотров')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Категория поста')),
            ],
            options={
                'verbose_name': 'Структура проекта',
                'verbose_name_plural': 'Структуры проектов',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='PostPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название фото')),
                ('url', models.URLField(verbose_name='Ссылка на фото')),
                ('order', models.PositiveSmallIntegerField(help_text='Будет использоваться для сортировки', verbose_name='Порядковый номер')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='blog.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Фото к посту',
                'verbose_name_plural': 'Фото к постам',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Имя автора комментария')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('public', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.comment', verbose_name='Ответ на комментарий')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='blog.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-pub_date',),
            },
        ),
    ]
