# Generated by Django 3.1.4 on 2020-12-17 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('order',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
