# Generated by Django 3.1.4 on 2020-12-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201218_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postphoto',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Будет использоваться для сортировки', null=True, verbose_name='Порядковый номер'),
        ),
    ]
