# Generated by Django 3.1.4 on 2020-12-17 19:45

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(help_text='Будет отображено в общих списках проектов, а также в теге description', verbose_name='Краткое описание (отображается в списке)')),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Краткое описание проекта (отображается на странице проекта)')),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полное описание проекта')),
                ('image', models.URLField(verbose_name='Картинка проекта')),
                ('order', models.PositiveSmallIntegerField(help_text='Необходим для сортировки проектов в списках', verbose_name='Порядковый номер проекта')),
                ('slug', models.SlugField(help_text='только маленькие латинские буквы, без пробелов и спец символов', unique=True, verbose_name='Slug')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации проекта')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Изменения')),
                ('views', models.PositiveSmallIntegerField(default=0, verbose_name='Количество просмотров')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='companies.company', verbose_name='Компания')),
                ('project_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='companies.profile', verbose_name='Администратор проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Краткое описание')),
                ('seo_description', ckeditor_uploader.fields.RichTextUploadingField(help_text='Может дублировать краткое описание', verbose_name='Краткое описание (для СЕО)')),
                ('miniature', models.URLField(verbose_name='Миниатюра (ссылка на изображение)')),
                ('image', models.URLField(verbose_name='Изображение проекта')),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полное описание')),
                ('order', models.PositiveSmallIntegerField(help_text='Будет использоваться для сортировки', verbose_name='Порядковый номер')),
                ('slug', models.SlugField(help_text='только маленькие латинские буквы, без пробелов и спец символов', unique=True, verbose_name='Slug')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Структура проекта',
                'verbose_name_plural': 'Структуры проектов',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Имя')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('professional', models.CharField(max_length=255, verbose_name='Профессия')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='Аватар (ссылка на изображение) необзятелно')),
                ('order', models.PositiveSmallIntegerField(help_text='Будет использоваться для сортировки', verbose_name='Порядковый номер')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Отзыв о проекте',
                'verbose_name_plural': 'Отзывы о проектах',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='QuestionAndAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(db_index=True, max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('order', models.PositiveSmallIntegerField(help_text='Будет использоваться для сортировки', verbose_name='Порядковый номер')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Вопрос и ответ',
                'verbose_name_plural': 'Вопросы и ответы',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ProjectVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название видео')),
                ('url', models.URLField(default='https://www.youtube.com/embed/', help_text='Скопировать и вставить конечный параметр ссылки после знака =', verbose_name='Ссылка на видео')),
                ('order', models.PositiveSmallIntegerField(help_text='Будет использоваться для сортировки', verbose_name='Порядковый номер')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Видео о проекте',
                'verbose_name_plural': 'Видео о проектах',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название фото')),
                ('url', models.URLField(verbose_name='Ссылка на фото')),
                ('order', models.PositiveSmallIntegerField(help_text='Будет использоваться для сортировки', verbose_name='Порядковый номер')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Фото к проекту',
                'verbose_name_plural': 'Фото к проектам',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='DigitalIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Заголовок показателя')),
                ('value', models.CharField(help_text='Например: 80%', max_length=30, verbose_name='Значение показателя')),
                ('max_value', models.CharField(help_text='Например: 100%', max_length=30, verbose_name='Макимально возможное значение')),
                ('order', models.PositiveSmallIntegerField(help_text='Будет использоваться для сортировки', verbose_name='Порядковый номер')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Цифровой показатель проекта',
                'verbose_name_plural': 'Цифровые показатели проектов',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(default='mdi-', help_text='Смотреть на сайте https://materialdesignicons.com/', max_length=100, verbose_name='Иконка')),
                ('order', models.PositiveSmallIntegerField(help_text='Будет использоваться для сортировки', verbose_name='Порядковый номер')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benefits', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Преимущество проекта',
                'verbose_name_plural': 'Преимущества проектов',
                'ordering': ('order',),
            },
        ),
    ]
