# Generated by Django 3.1.4 on 2020-12-18 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название файла')),
                ('url', models.URLField(verbose_name='Ссылка на файл')),
                ('order', models.PositiveSmallIntegerField(help_text='Будет использоваться для сортировки', verbose_name='Порядковый номер')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Файл к проекту',
                'verbose_name_plural': 'Файлы к проектам',
                'ordering': ('order',),
            },
        ),
    ]
