# Generated by Django 3.1.4 on 2020-12-17 19:45

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_partner', models.BooleanField(default=False, verbose_name='Партнер')),
                ('is_coach', models.BooleanField(default=False, verbose_name='Коуч')),
                ('is_investor', models.BooleanField(default=False, verbose_name='Инвестор')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон')),
                ('whatsapp', models.CharField(blank=True, max_length=30, null=True, verbose_name='Whatsapp (необязательно)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email (Необязательно)')),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Информация о пользователе(био)')),
                ('professional', models.CharField(blank=True, max_length=255, null=True, verbose_name='Профессия')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='Аватар (ссылка)')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Ссылка на профиль в Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Ссылка на профиль в Instagram')),
                ('vkontakte', models.URLField(blank=True, null=True, verbose_name='Ссылка на профиль в Контакте')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации на сайте')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь на сайте')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название компании')),
                ('description', models.TextField(verbose_name='Краткое описание (род деятельности)')),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полное описание компании')),
                ('logo', models.URLField(verbose_name='Логотип (ссылка)')),
                ('requisites', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Реквизиты компании')),
                ('address', models.TextField(verbose_name='Адрес компании')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='Whatsapp')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Ссылка на профиль в Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Ссылка на профиль в Instagram')),
                ('vkontakte', models.URLField(blank=True, null=True, verbose_name='Ссылка на профиль в Контакте')),
                ('slug', models.SlugField(help_text='только маленькие латинские буквы, без пробелов и спец символов', unique=True, verbose_name='Slug')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации компании на сайте')),
                ('admin_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='companies.profile', verbose_name='Администратор компании')),
                ('cooperators', models.ManyToManyField(blank=True, related_name='cooperators', to='companies.Profile', verbose_name='Сотрудники компании')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
    ]
