# Generated by Django 3.1.4 on 2020-12-18 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20201218_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_coach',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_investor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_partner',
        ),
    ]
