# Generated by Django 3.1.4 on 2020-12-18 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cipwiuim', '0001_initial'),
        ('companies', '0003_auto_20201219_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='partner_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='cipwiuim.cippartnerform', verbose_name='Форма партнерства'),
        ),
    ]
