# Generated by Django 3.1.4 on 2020-12-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_profile_partner_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uID',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID пользователя (Firebase)'),
        ),
    ]
