# Generated by Django 3.1.4 on 2020-12-17 21:47

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_auto_20201218_0316'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Краткое описание темы')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Тема')),
                ('order', models.PositiveSmallIntegerField(help_text='Будет использоваться для сортировки', verbose_name='Порядковый номер')),
                ('slug', models.SlugField(help_text='только маленькие латинские буквы, без пробелов и спец символов', unique=True, verbose_name='Slug')),
                ('views', models.PositiveSmallIntegerField(default=0, verbose_name='Количество просмотров')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes', to='companies.profile', verbose_name='Автор темы')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_themes', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Тема форума',
                'verbose_name_plural': 'Темы форума',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя автора')),
                ('text', models.TextField(max_length=7000, verbose_name='Сообщение')),
                ('public', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('answer_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.answer', verbose_name='Ответ на сообщение от')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='companies.profile', verbose_name='Автор темы')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='forum.theme', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ('-pub_date',),
            },
        ),
    ]
