# Generated by Django 3.1.4 on 2021-02-17 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_profile_uid'),
        ('forum', '0003_theme_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='forum.answer', verbose_name='Ответ на сообщение от'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='companies.profile', verbose_name='Профиль автора сообщения'),
        ),
    ]
