# Generated by Django 3.1.4 on 2020-12-19 14:58

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название области или региона')),
                ('slug', models.SlugField(help_text='только маленькие латинские буквы, без пробелов и спец символов', unique=True, verbose_name='Slug')),
                ('order', models.PositiveSmallIntegerField(help_text='Будет использоваться для сортировки', verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='MapPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('x', models.FloatField(null=True, verbose_name='Координата Х')),
                ('y', models.FloatField(null=True, verbose_name='Координата y')),
                ('map_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок для объекта на карте (необязательно)')),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(help_text='Будет отображаться на карте', verbose_name='Краткое описание')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полное описание')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points', to='map_points.region', verbose_name='Область или регион')),
            ],
            options={
                'verbose_name': 'Объект на карте',
                'verbose_name_plural': 'Объекты на карте',
            },
        ),
    ]
