# Generated by Django 3.1.4 on 2021-04-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_points', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappoint',
            name='x',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='y',
        ),
        migrations.AddField(
            model_name='mappoint',
            name='coordinates',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Координаты'),
        ),
    ]
