# Generated by Django 3.1.4 on 2021-04-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_points', '0002_auto_20210424_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappoint',
            name='map_title',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='short_description',
        ),
        migrations.AddField(
            model_name='mappoint',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Изображение'),
        ),
    ]
