# Generated by Django 3.1.4 on 2021-04-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_points', '0003_auto_20210424_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название отрасли')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Отрасль',
                'verbose_name_plural': 'Отрасли',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='mappoint',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='points', to='map_points.PointType', verbose_name='Отрасль'),
        ),
    ]
