# Generated by Django 3.1.4 on 2021-04-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_points', '0004_auto_20210424_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointtype',
            name='slug',
            field=models.SlugField(blank=True, help_text='только маленькие латинские буквы, без пробелов и спец символов', null=True, unique=True, verbose_name='Slug'),
        ),
    ]
