# Generated by Django 3.1.4 on 2021-04-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_points', '0005_pointtype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='coordinates',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Координаты региона'),
        ),
    ]
