# Generated by Django 3.1.4 on 2021-05-07 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_points', '0007_mappointimage_mappointvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappointvideo',
            name='map_point',
        ),
        migrations.DeleteModel(
            name='MapPointImage',
        ),
        migrations.DeleteModel(
            name='MapPointVideo',
        ),
    ]
