# Generated by Django 3.1.4 on 2020-12-18 21:28

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CIPAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, default='CipWiuim', max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полное описание компании')),
                ('logo', models.URLField(verbose_name='Ссылка на изображение (логотип)')),
            ],
            options={
                'verbose_name': 'Информация о компании',
                'verbose_name_plural': 'Информация о компании',
            },
        ),
        migrations.CreateModel(
            name='CIPPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название компании-партнера')),
                ('logo', models.URLField(verbose_name='Логотип партнера (ссылка на лого)')),
                ('url', models.URLField(verbose_name='Ссылка на сайт партнера')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='CIPPartnerForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('short_description', models.TextField(help_text='Будет выводится на главной странице', verbose_name='Краткое описание')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полное описание')),
                ('image', models.URLField(verbose_name='Ссылка на картинку')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Форма партнерства',
                'verbose_name_plural': 'Формы партнерства',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='CIPQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('order', models.PositiveSmallIntegerField(help_text='Необходим для сортировки вопросов', verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Вопрос и ответ',
                'verbose_name_plural': 'Вопросы и ответы',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='CIPReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('text', models.TextField(verbose_name='Текст отзыва или мнения')),
                ('position', models.CharField(help_text='Например: должность', max_length=100, verbose_name='Дополнительно')),
            ],
            options={
                'verbose_name': 'Отзыв или мнение',
                'verbose_name_plural': 'Отзывы и мнения',
            },
        ),
        migrations.CreateModel(
            name='ForPartnerNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст уведомления')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания уведомления')),
                ('partner_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='cipwiuim.cippartnerform', verbose_name='Форма партнерста')),
            ],
            options={
                'verbose_name': 'Уведомление для партнера',
                'verbose_name_plural': 'Уведомления для партнеров',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Указать для кого правила. Например: общие или для инвесторов', max_length=255, verbose_name='Заголовок')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полное описание')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Правило пользования сайтом',
                'verbose_name_plural': 'Правила пользования сайтом',
            },
        ),
        migrations.CreateModel(
            name='PartnerFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название файла')),
                ('url', models.URLField(verbose_name='Ссылка на файл')),
                ('partner_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, related_name='files', to='cipwiuim.cippartnerform', verbose_name='Форма партнества')),
            ],
            options={
                'verbose_name': 'Файл для партнеров',
                'verbose_name_plural': 'Файлы для партнеров',
            },
        ),
        migrations.CreateModel(
            name='NotificationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название файла')),
                ('url', models.URLField(verbose_name='Ссылка на файл')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, related_name='files', to='cipwiuim.forpartnernotification', verbose_name='Уведомление')),
            ],
            options={
                'verbose_name': 'Файл к уведомлению',
                'verbose_name_plural': 'Файлы к уведомлениям',
            },
        ),
    ]
