# Generated by Django 3.1.4 on 2020-12-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cipwiuim', '0002_auto_20201219_0354'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIPPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название фото')),
                ('url', models.URLField(verbose_name='Ссылка на фото')),
                ('order', models.PositiveSmallIntegerField(help_text='Будет использоваться для сортировки', verbose_name='Порядковый номер')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотогалерея',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='CIPVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название видео')),
                ('url', models.URLField(default='https://www.youtube.com/embed/', help_text='Скопировать и вставить конечный параметр ссылки после знака =', verbose_name='Ссылка на видео')),
                ('order', models.PositiveSmallIntegerField(help_text='Будет использоваться для сортировки', verbose_name='Порядковый номер')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видеогалерея',
                'ordering': ('order',),
            },
        ),
    ]
