# Generated by Django 3.1.4 on 2020-12-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cipwiuim', '0003_cipphoto_cipvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cippartnerform',
            name='banner',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на баннер'),
        ),
        migrations.AddField(
            model_name='cippartnerform',
            name='banner_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок на баннере'),
        ),
    ]
