# Generated by Django 3.1.4 on 2020-12-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cipwiuim', '0004_auto_20201230_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110, verbose_name='Title сайта')),
                ('description', models.TextField(max_length=190, verbose_name='Описание сайта')),
                ('logo', models.URLField(verbose_name='Ссылка на лого сайта')),
            ],
            options={
                'verbose_name': 'Главная страница СЕО',
                'verbose_name_plural': 'Главная страцниа СЕО',
            },
        ),
        migrations.CreateModel(
            name='SliderSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Заголовок слайда')),
                ('text', models.TextField(verbose_name='Текст на слайдере')),
                ('image', models.URLField(verbose_name='Ссылка на изображение')),
                ('button_text', models.CharField(max_length=50, verbose_name='Текст на кнопке')),
                ('button_url', models.URLField(verbose_name='Ссылка кнопки')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Опрядковый номер слайда')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайдер',
                'ordering': ('order',),
            },
        ),
    ]
