# Generated by Django 3.1.4 on 2020-12-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cipwiuim', '0005_homepage_sliderslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderslide',
            name='button_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка кнопки'),
        ),
        migrations.AlterField(
            model_name='sliderslide',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='Порядковый номер слайда'),
        ),
    ]
