# Generated by Django 3.1.4 on 2021-04-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cipwiuim', '0006_auto_20201231_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='cippartnerform',
            name='register_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на регистрацию'),
        ),
    ]
