# Generated by Django 3.1.4 on 2021-03-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20201230_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Заметка')),
                ('complete', models.BooleanField(default=False, verbose_name='Обработана')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки на консультацию',
                'ordering': ('-date',),
            },
        ),
    ]
